export const amenityIcons = {
  "Sunny weather": "☀️",
  "Onsite zoo": "🦓",
  Sea: "🌊",
  Nature: "🌲",
  "Water sports": "🤽",
  "Free WiFi": "📶",
  "Pet friendly": "🐾",
  "Spa services": "💆",
  "Fitness center": "🏋️",
  "Airport shuttle": "✈️",
  "Free parking": "🅿️",
  Restaurant: "🍴",
  "Swimming pool": "🏊",
  Bar: "🍹",
  Elevator: "🛗",
  Fan: "🌀",
  Monitor: "🖥️",
};
